//! Data types shared across the state modules: what is stored in Redis, what
//! is sent to clients, and the tokens that tie an AudioPlayer directive back to
//! the queue entry that produced it. No Redis access lives here.

use super::now_f64;
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};

/// Failures closer than this are counted as consecutive. Retries arrive within
/// seconds, so this threshold is generous.
const FAILURE_RESET_SECS: f64 = 60.0;

// ── Playback tokens ──

/// Generate an AudioPlayer token / queue entry "{track_id}#{millis}".
/// Alexa ignores ENQUEUE with the same token as the current one, so each play
/// must produce a unique token.
pub fn new_token(track_id: &str) -> String {
    let millis = (now_f64() * 1000.0) as u64;
    format!("{track_id}#{millis}")
}

/// Extract the track ID portion from a token / queue entry.
/// YouTube IDs never contain '#'.
pub fn token_track_id(token: &str) -> &str {
    token.split('#').next().unwrap_or(token)
}

/// Suffix appended by auto_token / checked by is_auto_token.
const AUTO_TOKEN_SUFFIX: &str = "#auto";

/// Build a token that marks auto-continued playback (loop/shuffle). If the
/// playback mode is switched to "off" after ENQUEUE, the directive cannot be
/// revoked, so PlaybackStarted uses this marker to stop playback.
pub fn auto_token(track_id: &str) -> String {
    format!("{}{AUTO_TOKEN_SUFFIX}", new_token(track_id))
}

/// Whether the token was generated by auto-continuation.
pub fn is_auto_token(token: &str) -> bool {
    token.ends_with(AUTO_TOKEN_SUFFIX)
}

// ── Data models ──

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AudioTrack {
    pub id: String,
    pub title: String,
    #[serde(default)]
    pub thumbnail: String,
    #[serde(default)]
    pub duration: u64,
    #[serde(default)]
    pub channel: String,
    #[serde(default)]
    pub is_live: bool,
    #[serde(default)]
    pub created_at: f64,
    /// Excluded from API responses; only included by to_redis_json for Redis.
    #[serde(skip)]
    pub file_path: String,
}

impl AudioTrack {
    /// Redis representation: the API shape plus the internal file path, which is
    /// serde(skip)ped so it never reaches clients. Callers report the failure
    /// rather than panicking, matching write_device.
    pub(crate) fn to_redis_json(&self) -> serde_json::Result<String> {
        let mut v = serde_json::to_value(self)?;
        v["file_path"] = json!(self.file_path);
        Ok(v.to_string())
    }

    pub(crate) fn extract_channel(meta: &Value) -> String {
        meta["channel"]
            .as_str()
            .or(meta["uploader"].as_str())
            .unwrap_or("")
            .to_string()
    }

    pub(crate) fn from_meta(id: &str, meta: &Value, created_at: f64, file_path: String) -> Self {
        Self {
            id: id.to_string(),
            title: meta["title"].as_str().unwrap_or(id).to_string(),
            thumbnail: meta["thumbnail"].as_str().unwrap_or("").to_string(),
            duration: meta["duration"].as_u64().unwrap_or(0),
            channel: Self::extract_channel(meta),
            is_live: meta["is_live"].as_bool().unwrap_or(false),
            created_at,
            file_path,
        }
    }

    pub(crate) fn from_redis_json(s: &str) -> Option<Self> {
        let v: Value = serde_json::from_str(s).ok()?;
        let file_path = v["file_path"].as_str()?.to_string();
        let mut track: Self = serde_json::from_value(v).ok()?;
        track.file_path = file_path;
        Some(track)
    }
}

/// Named playlist. Track IDs are stored in a separate list (youtube:playlist:{id}).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Playlist {
    pub id: String,
    pub name: String,
    pub created_at: f64,
}

/// Wire format for playlists_json: metadata with track count.
#[derive(Serialize)]
pub(crate) struct PlaylistJson {
    #[serde(flatten)]
    pub(crate) playlist: Playlist,
    pub(crate) count: usize,
}

/// Info returned when a playlist import starts (import runs in the background).
pub struct PlaylistImportInfo {
    pub name: String,
    pub total: usize,
}

/// Result of reorder_track. Lets callers distinguish "not in list" (not enrolled
/// or concurrently deleted) from Redis errors.
pub enum ReorderOutcome {
    Moved,
    NotInList,
    Failed,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeviceState {
    pub device_id: String,
    pub name: String,
    pub status: String,
    pub current_track: Option<AudioTrack>,
    pub position_ms: u64,
    pub connected: bool,
    pub last_update: f64,
}

impl DeviceState {
    /// Apply an update and advance last_update to `now`. All device state
    /// changes must go through this method — position_ms means "position as of
    /// last_update", so advancing last_update alone would rewind the client's
    /// estimated position.
    pub(crate) fn apply(&mut self, upd: DeviceUpdate, now: f64) {
        // Updates without an explicit position (e.g. re-registration) advance
        // position by elapsed time to stay consistent.
        if upd.position_ms.is_none() {
            self.advance_position(now);
        }
        if let Some(s) = upd.status {
            self.status = s;
        }
        if let Some(t) = upd.current_track {
            self.current_track = Some(t);
        }
        if let Some(p) = upd.position_ms {
            self.position_ms = p;
        }
        self.last_update = now;
    }

    /// Whether playback is in progress (playing or paused). Used to decide
    /// whether to auto-start the Up Next queue on launch.
    pub fn playback_in_progress(&self) -> bool {
        matches!(self.status.as_str(), "playing" | "paused")
    }

    /// Advance position by elapsed time while playing (clamped to track end).
    fn advance_position(&mut self, now: f64) {
        if self.status != "playing" {
            return;
        }
        let elapsed_ms = ((now - self.last_update).max(0.0) * 1000.0) as u64;
        let max_ms = self
            .current_track
            .as_ref()
            .map(|t| t.duration.saturating_mul(1000))
            .filter(|&d| d > 0)
            .unwrap_or(u64::MAX);
        self.position_ms = self.position_ms.saturating_add(elapsed_ms).min(max_ms);
    }
}

/// Per-track consecutive playback failure record. Used to decide when to stop
/// retrying PlaybackFailed. Kept in-process only; reset on restart.
#[derive(Debug, Default)]
pub(crate) struct FailureRecord {
    count: u32,
    last_failure: f64,
    /// Playback position (ms) at last failure. If position has advanced since
    /// then, the retry succeeded, so it is not counted as consecutive.
    last_offset: u64,
}

impl FailureRecord {
    /// Record a failure and return the consecutive count (including this one).
    /// Resets to 1 if more than FAILURE_RESET_SECS have passed since the last
    /// failure, or if the position has advanced (proving an intervening success).
    pub(crate) fn record(&mut self, offset_ms: u64, now: f64) -> u32 {
        if now - self.last_failure > FAILURE_RESET_SECS || offset_ms > self.last_offset {
            self.count = 0;
        }
        self.count += 1;
        self.last_failure = now;
        self.last_offset = offset_ms;
        self.count
    }
}

/// A single Up Next queue item (for API responses).
#[derive(Serialize)]
pub struct QueueItem {
    /// Unique entry within the queue ("{track_id}#{millis}"). Used to identify items for removal.
    pub entry: String,
    #[serde(flatten)]
    pub track: AudioTrack,
}

/// Wire format for devices_json: device state plus Up Next queue. Kept separate
/// from DeviceState to avoid write_device persisting queue data to Redis.
#[derive(Serialize)]
pub(crate) struct DeviceJson {
    #[serde(flatten)]
    pub(crate) device: DeviceState,
    pub(crate) queue: Vec<QueueItem>,
}

/// Download stage. Lowercase wire format must match the frontend
/// DownloadProgress["status"] union.
#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum DownloadStatus {
    /// Fetching metadata (before title / live detection is resolved).
    Metadata,
    Downloading,
    /// Post-processing by yt-dlp (conversion to m4a).
    Processing,
    Error,
}

/// In-progress download progress. Kept in-process and broadcast to all
/// WebSocket clients so any browser (including after a reload) can track it.
#[derive(Debug, Clone, Serialize)]
pub struct DownloadProgress {
    pub id: String,
    /// Filled with the video ID before metadata is fetched.
    pub title: String,
    pub status: DownloadStatus,
    /// Download progress percentage (0.0–100.0).
    pub percent: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// Start time (UNIX seconds). Used for display order and identity check
    /// when cleaning up errors.
    pub started_at: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PendingCommand {
    pub action: String,
    pub track: AudioTrack,
    /// Playback start position in milliseconds. Non-zero when seeking from web.
    #[serde(default)]
    pub offset_ms: u64,
}

// API request types
#[derive(Deserialize)]
pub struct PlayRequest {
    pub track_id: String,
    pub device_ids: Vec<String>,
}

#[derive(Deserialize)]
pub struct SeekRequest {
    /// Seek target in milliseconds (clamped to just before track end).
    pub position_ms: u64,
}

#[derive(Deserialize)]
pub struct ReorderRequest {
    pub track_id: String,
    /// Target index (0-based, clamped to list end if out of range).
    pub new_index: usize,
    /// Playlist ID to reorder within (omit for library-wide order).
    #[serde(default)]
    pub playlist: Option<String>,
}

// ── DeviceUpdate builder ──

#[derive(Default)]
pub struct DeviceUpdate {
    status: Option<String>,
    current_track: Option<AudioTrack>,
    position_ms: Option<u64>,
}

impl DeviceUpdate {
    pub fn new() -> Self {
        Self::default()
    }
    pub fn status(mut self, s: impl Into<String>) -> Self {
        self.status = Some(s.into());
        self
    }
    pub fn track(mut self, t: AudioTrack) -> Self {
        self.current_track = Some(t);
        self
    }
    pub fn position(mut self, p: u64) -> Self {
        self.position_ms = Some(p);
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn redis_json_roundtrip_preserves_is_live() {
        let track = AudioTrack {
            id: "dQw4w9WgXcQ".into(),
            title: "配信".into(),
            thumbnail: String::new(),
            duration: 0,
            channel: "ch".into(),
            is_live: true,
            created_at: 1.0,
            file_path: String::new(),
        };
        let restored = AudioTrack::from_redis_json(&track.to_redis_json().unwrap()).unwrap();
        assert!(restored.is_live);
        assert!(restored.file_path.is_empty());
    }

    #[test]
    fn token_roundtrip_preserves_track_id() {
        let token = new_token("dQw4w9WgXcQ");
        assert_eq!(token_track_id(&token), "dQw4w9WgXcQ");
        // Also accepts values without '#' (legacy format or bare track IDs)
        assert_eq!(token_track_id("dQw4w9WgXcQ"), "dQw4w9WgXcQ");
    }

    #[test]
    fn auto_token_is_detectable_and_preserves_track_id() {
        let token = auto_token("dQw4w9WgXcQ");
        assert!(is_auto_token(&token));
        assert_eq!(token_track_id(&token), "dQw4w9WgXcQ");
        // Normal tokens and queue entries are not detected as auto-selected
        assert!(!is_auto_token(&new_token("dQw4w9WgXcQ")));
        assert!(!is_auto_token("dQw4w9WgXcQ"));
    }

    #[test]
    fn queue_item_serializes_flattened() {
        let item = QueueItem {
            entry: "dQw4w9WgXcQ#123".into(),
            track: AudioTrack {
                id: "dQw4w9WgXcQ".into(),
                title: "t".into(),
                thumbnail: String::new(),
                duration: 10,
                channel: String::new(),
                is_live: false,
                created_at: 0.0,
                file_path: "/tmp/a.m4a".into(),
            },
        };
        let v = serde_json::to_value(&item).unwrap();
        // entry and track fields are flattened at the same level (file_path is not exposed)
        assert_eq!(v["entry"], "dQw4w9WgXcQ#123");
        assert_eq!(v["id"], "dQw4w9WgXcQ");
        assert!(v.get("file_path").is_none());
    }

    #[test]
    fn pending_command_without_offset_defaults_to_zero() {
        // Pending commands queued before offset_ms was introduced should still parse
        let legacy = r#"{"action":"play","track":{"id":"dQw4w9WgXcQ","title":"t"}}"#;
        let cmd: PendingCommand = serde_json::from_str(legacy).unwrap();
        assert_eq!(cmd.offset_ms, 0);
    }

    /// A device playing a 10-second track at position 5s with last_update 100.0.
    fn playing_device() -> DeviceState {
        DeviceState {
            device_id: "d".into(),
            name: "n".into(),
            status: "playing".into(),
            current_track: Some(AudioTrack {
                id: "dQw4w9WgXcQ".into(),
                title: "t".into(),
                thumbnail: String::new(),
                duration: 10,
                channel: String::new(),
                is_live: false,
                created_at: 0.0,
                file_path: String::new(),
            }),
            position_ms: 5_000,
            connected: true,
            last_update: 100.0,
        }
    }

    #[test]
    fn advance_position_only_moves_while_playing_and_clamps_to_duration() {
        let mut dev = playing_device();
        dev.advance_position(102.0);
        assert_eq!(dev.position_ms, 7_000);

        // Clamp at track end
        dev.last_update = 102.0;
        dev.advance_position(200.0);
        assert_eq!(dev.position_ms, 10_000);

        // Don't advance if not playing
        dev.status = "paused".into();
        dev.position_ms = 1_000;
        dev.advance_position(300.0);
        assert_eq!(dev.position_ms, 1_000);
    }

    #[test]
    fn apply_keeps_position_consistent_with_last_update() {
        // Even without an explicit position, the estimated position doesn't rewind
        let mut dev = playing_device();
        dev.apply(DeviceUpdate::new(), 102.0);
        assert_eq!(dev.position_ms, 7_000);
        assert_eq!(dev.last_update, 102.0);

        // Explicit position is adopted as-is
        let mut dev = playing_device();
        dev.apply(DeviceUpdate::new().position(1_000), 102.0);
        assert_eq!(dev.position_ms, 1_000);
        assert_eq!(dev.last_update, 102.0);
    }

    #[test]
    fn failure_record_counts_consecutive_failures() {
        let mut rec = FailureRecord::default();

        // Consecutive as long as failures happen at the same position
        assert_eq!(rec.record(5_000, 100.0), 1);
        assert_eq!(rec.record(5_000, 105.0), 2);
        assert_eq!(rec.record(5_000, 110.0), 3);

        // A failure at a later position resets the count (evidence of a successful retry in between)
        assert_eq!(rec.record(30_000, 115.0), 1);

        // A failure that hasn't advanced (e.g. restart failure) counts as consecutive
        assert_eq!(rec.record(0, 120.0), 2);

        // A failure more than FAILURE_RESET_SECS after the last one also resets
        assert_eq!(rec.record(0, 120.0 + FAILURE_RESET_SECS + 1.0), 1);
    }

    #[test]
    fn download_status_serializes_lowercase() {
        // Pin the wire format to match the frontend (types.ts) status union
        for (status, expected) in [
            (DownloadStatus::Metadata, "metadata"),
            (DownloadStatus::Downloading, "downloading"),
            (DownloadStatus::Processing, "processing"),
            (DownloadStatus::Error, "error"),
        ] {
            assert_eq!(serde_json::to_value(status).unwrap(), json!(expected));
        }
    }

    #[test]
    fn redis_json_without_is_live_defaults_to_false() {
        let legacy = r#"{"id":"dQw4w9WgXcQ","title":"t","thumbnail":"","duration":10,"channel":"","created_at":1.0,"file_path":"/tmp/a.m4a"}"#;
        let track = AudioTrack::from_redis_json(legacy).unwrap();
        assert!(!track.is_live);
    }
}
