use redis::AsyncCommands;
use redis::aio::ConnectionManager;
use regex::Regex;
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};
use tokio::io::{AsyncBufReadExt, AsyncReadExt, BufReader};
use tokio::process::Command;
use tokio::sync::{Mutex, broadcast};
use tokio::time;

const REDIS_KEY_ACTIVE_PLAYLIST: &str = "youtube:active_playlist";
const REDIS_KEY_DEVICES: &str = "youtube:devices";
const REDIS_KEY_PLAYBACK_MODE: &str = "youtube:playback_mode";
const REDIS_KEY_PLAYLISTS: &str = "youtube:playlists";
const REDIS_KEY_SLEEP_TIMER: &str = "youtube:sleep_timer";
const REDIS_KEY_TRACKS: &str = "youtube:tracks";
const REDIS_KEY_TRACKS_ORDER: &str = "youtube:tracks_order";
const REDIS_PENDING_PREFIX: &str = "youtube:pending";
const REDIS_PLAYLIST_PREFIX: &str = "youtube:playlist";
/// Each entry is a unique "{track_id}#{millis}" string used as the AudioPlayer
/// token, so playback events can match and consume entries by value.
const REDIS_QUEUE_PREFIX: &str = "youtube:queue";

const PLAYBACK_MODES: [&str; 3] = ["loop", "shuffle", "off"];
const DEFAULT_PLAYBACK_MODE: &str = "off";

const PLAYLIST_NAME_MAX_CHARS: usize = 100;
/// Cap for playlist import to avoid expanding effectively-infinite mix lists.
const PLAYLIST_IMPORT_MAX: usize = 100;
const PLAYLIST_FLAT_TIMEOUT_SECS: u64 = 60;

/// Pending command TTL in seconds (expired by Redis key TTL).
const PENDING_TTL_SECS: u64 = 600;

/// Keep failed download progress visible for a while so reloading clients can
/// still see the error.
const DOWNLOAD_ERROR_TTL_SECS: u64 = 60;
/// Failures closer than this are counted as consecutive. Retries arrive within
/// seconds, so this threshold is generous.
const FAILURE_RESET_SECS: f64 = 60.0;
/// Per-item timeout for metadata fetches to prevent yt-dlp from stalling.
const METADATA_TIMEOUT_SECS: u64 = 30;
/// Prefix added via --progress-template to distinguish progress lines.
const PROGRESS_PREFIX: &str = "__progress__ ";
const VIDEO_ID_PATTERN: &str = "[a-zA-Z0-9_-]{11}";

/// Cached audio format extension. Must be kept in sync with AUDIO_MIME.
const AUDIO_EXT: &str = "m4a";
pub const AUDIO_MIME: &str = "audio/mp4";

fn pending_key(device_id: &str) -> String {
    format!("{REDIS_PENDING_PREFIX}:{device_id}")
}

fn queue_key(device_id: &str) -> String {
    format!("{REDIS_QUEUE_PREFIX}:{device_id}")
}

fn playlist_key(playlist_id: &str) -> String {
    format!("{REDIS_PLAYLIST_PREFIX}:{playlist_id}")
}

/// Generate an AudioPlayer token / queue entry "{track_id}#{millis}".
/// Alexa ignores ENQUEUE with the same token as the current one, so each play
/// must produce a unique token.
pub fn new_token(track_id: &str) -> String {
    let millis = (now_f64() * 1000.0) as u64;
    format!("{track_id}#{millis}")
}

/// Extract the track ID portion from a token / queue entry.
/// YouTube IDs never contain '#'.
pub fn token_track_id(token: &str) -> &str {
    token.split('#').next().unwrap_or(token)
}

/// Suffix appended by auto_token / checked by is_auto_token.
const AUTO_TOKEN_SUFFIX: &str = "#auto";

/// Build a token that marks auto-continued playback (loop/shuffle). If the
/// playback mode is switched to "off" after ENQUEUE, the directive cannot be
/// revoked, so PlaybackStarted uses this marker to stop playback.
pub fn auto_token(track_id: &str) -> String {
    format!("{}{AUTO_TOKEN_SUFFIX}", new_token(track_id))
}

/// Whether the token was generated by auto-continuation.
pub fn is_auto_token(token: &str) -> bool {
    token.ends_with(AUTO_TOKEN_SUFFIX)
}

// ════════════════════════════════════════
// Data models
// ════════════════════════════════════════

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AudioTrack {
    pub id: String,
    pub title: String,
    #[serde(default)]
    pub thumbnail: String,
    #[serde(default)]
    pub duration: u64,
    #[serde(default)]
    pub channel: String,
    #[serde(default)]
    pub is_live: bool,
    #[serde(default)]
    pub created_at: f64,
    /// Excluded from API responses; only included by to_redis_json for Redis.
    #[serde(skip)]
    pub file_path: String,
}

impl AudioTrack {
    fn to_redis_json(&self) -> String {
        let mut v = serde_json::to_value(self).expect("AudioTrack serializes to JSON");
        v["file_path"] = json!(self.file_path);
        v.to_string()
    }

    /// Build a track from yt-dlp metadata JSON.
    /// Missing fields are filled with empty values (title falls back to ID).
    fn from_meta(id: &str, meta: &Value, created_at: f64, file_path: String) -> Self {
        Self {
            id: id.to_string(),
            title: meta["title"].as_str().unwrap_or(id).to_string(),
            thumbnail: meta["thumbnail"].as_str().unwrap_or("").to_string(),
            duration: meta["duration"].as_u64().unwrap_or(0),
            channel: meta["channel"]
                .as_str()
                .or(meta["uploader"].as_str())
                .unwrap_or("")
                .to_string(),
            is_live: meta["is_live"].as_bool().unwrap_or(false),
            created_at,
            file_path,
        }
    }

    fn from_redis_json(s: &str) -> Option<Self> {
        let v: Value = serde_json::from_str(s).ok()?;
        let file_path = v["file_path"].as_str()?.to_string();
        let mut track: Self = serde_json::from_value(v).ok()?;
        track.file_path = file_path;
        Some(track)
    }
}

/// Named playlist. Track IDs are stored in a separate list (youtube:playlist:{id}).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Playlist {
    pub id: String,
    pub name: String,
    pub created_at: f64,
}

/// Wire format for playlists_json: metadata with track count.
#[derive(Serialize)]
struct PlaylistJson {
    #[serde(flatten)]
    playlist: Playlist,
    count: usize,
}

/// Info returned when a playlist import starts (import runs in the background).
pub struct PlaylistImportInfo {
    pub name: String,
    pub total: usize,
}

/// Result of reorder_track. Lets callers distinguish "not in list" (not enrolled
/// or concurrently deleted) from Redis errors.
pub enum ReorderOutcome {
    Moved,
    NotInList,
    Failed,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeviceState {
    pub device_id: String,
    pub name: String,
    pub status: String,
    pub current_track: Option<AudioTrack>,
    pub position_ms: u64,
    pub connected: bool,
    pub last_update: f64,
}

impl DeviceState {
    /// Apply an update and advance last_update to `now`. All device state
    /// changes must go through this method — position_ms means "position as of
    /// last_update", so advancing last_update alone would rewind the client's
    /// estimated position.
    fn apply(&mut self, upd: DeviceUpdate, now: f64) {
        // Updates without an explicit position (e.g. re-registration) advance
        // position by elapsed time to stay consistent.
        if upd.position_ms.is_none() {
            self.advance_position(now);
        }
        if let Some(s) = upd.status {
            self.status = s;
        }
        if let Some(t) = upd.current_track {
            self.current_track = Some(t);
        }
        if let Some(p) = upd.position_ms {
            self.position_ms = p;
        }
        self.last_update = now;
    }

    /// Whether playback is in progress (playing or paused). Used to decide
    /// whether to auto-start the Up Next queue on launch.
    pub fn playback_in_progress(&self) -> bool {
        matches!(self.status.as_str(), "playing" | "paused")
    }

    /// Advance position by elapsed time while playing (clamped to track end).
    fn advance_position(&mut self, now: f64) {
        if self.status != "playing" {
            return;
        }
        let elapsed_ms = ((now - self.last_update).max(0.0) * 1000.0) as u64;
        let max_ms = self
            .current_track
            .as_ref()
            .map(|t| t.duration.saturating_mul(1000))
            .filter(|&d| d > 0)
            .unwrap_or(u64::MAX);
        self.position_ms = self.position_ms.saturating_add(elapsed_ms).min(max_ms);
    }
}

/// Per-track consecutive playback failure record. Used to decide when to stop
/// retrying PlaybackFailed. Kept in-process only; reset on restart.
#[derive(Debug, Default)]
struct FailureRecord {
    count: u32,
    last_failure: f64,
    /// Playback position (ms) at last failure. If position has advanced since
    /// then, the retry succeeded, so it is not counted as consecutive.
    last_offset: u64,
}

impl FailureRecord {
    /// Record a failure and return the consecutive count (including this one).
    /// Resets to 1 if more than FAILURE_RESET_SECS have passed since the last
    /// failure, or if the position has advanced (proving an intervening success).
    fn record(&mut self, offset_ms: u64, now: f64) -> u32 {
        if now - self.last_failure > FAILURE_RESET_SECS || offset_ms > self.last_offset {
            self.count = 0;
        }
        self.count += 1;
        self.last_failure = now;
        self.last_offset = offset_ms;
        self.count
    }
}

/// A single Up Next queue item (for API responses).
#[derive(Serialize)]
pub struct QueueItem {
    /// Unique entry within the queue ("{track_id}#{millis}"). Used to identify items for removal.
    pub entry: String,
    #[serde(flatten)]
    pub track: AudioTrack,
}

/// Wire format for devices_json: device state plus Up Next queue. Kept separate
/// from DeviceState to avoid write_device persisting queue data to Redis.
#[derive(Serialize)]
struct DeviceJson {
    #[serde(flatten)]
    device: DeviceState,
    queue: Vec<QueueItem>,
}

/// Download stage. Lowercase wire format must match the frontend
/// DownloadProgress["status"] union.
#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum DownloadStatus {
    /// Fetching metadata (before title / live detection is resolved).
    Metadata,
    Downloading,
    /// Post-processing by yt-dlp (conversion to m4a).
    Processing,
    Error,
}

/// In-progress download progress. Kept in-process and broadcast to all
/// WebSocket clients so any browser (including after a reload) can track it.
#[derive(Debug, Clone, Serialize)]
pub struct DownloadProgress {
    pub id: String,
    /// Filled with the video ID before metadata is fetched.
    pub title: String,
    pub status: DownloadStatus,
    /// Download progress percentage (0.0–100.0).
    pub percent: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// Start time (UNIX seconds). Used for display order and identity check
    /// when cleaning up errors.
    pub started_at: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PendingCommand {
    pub action: String,
    pub track: AudioTrack,
    /// Playback start position in milliseconds. Non-zero when seeking from web.
    #[serde(default)]
    pub offset_ms: u64,
}

// API request types
#[derive(Deserialize)]
pub struct PlayRequest {
    pub track_id: String,
    pub device_ids: Vec<String>,
}

#[derive(Deserialize)]
pub struct SeekRequest {
    /// Seek target in milliseconds (clamped to just before track end).
    pub position_ms: u64,
}

#[derive(Deserialize)]
pub struct ReorderRequest {
    pub track_id: String,
    /// Target index (0-based, clamped to list end if out of range).
    pub new_index: usize,
    /// Playlist ID to reorder within (omit for library-wide order).
    #[serde(default)]
    pub playlist: Option<String>,
}

// ════════════════════════════════════════
// DeviceUpdate builder
// ════════════════════════════════════════

#[derive(Default)]
pub struct DeviceUpdate {
    status: Option<String>,
    current_track: Option<AudioTrack>,
    position_ms: Option<u64>,
}

impl DeviceUpdate {
    pub fn new() -> Self {
        Self::default()
    }
    pub fn status(mut self, s: impl Into<String>) -> Self {
        self.status = Some(s.into());
        self
    }
    pub fn track(mut self, t: AudioTrack) -> Self {
        self.current_track = Some(t);
        self
    }
    pub fn position(mut self, p: u64) -> Self {
        self.position_ms = Some(p);
        self
    }
}

// ════════════════════════════════════════
// AppState — shared application state
// ════════════════════════════════════════

pub struct AppState {
    redis: ConnectionManager,
    pub tx: broadcast::Sender<String>,
    pub cache_dir: PathBuf,
    pub api_token: Option<String>,
    pub locale: String,
    /// Whether track restoration from audio_cache is in progress (prevents
    /// concurrent runs).
    restoring: AtomicBool,
    /// Serializes modifications to youtube:tracks_order so reorder's
    /// read-then-replace and extract/remove's LPUSH/LREM don't interleave.
    order_lock: Mutex<()>,
    /// Per-video lock to prevent concurrent downloads from writing the same
    /// output file simultaneously.
    extract_locks: Mutex<HashMap<String, Arc<Mutex<()>>>>,
    /// In-progress download progress (video ID → progress). In-process only;
    /// lost on restart (clients re-sync via the init snapshot).
    downloads: Mutex<HashMap<String, DownloadProgress>>,
    /// Bumped on cancel; each import captures the value at start and stops
    /// when it changes, so concurrent imports are all cancelled correctly.
    import_cancel_gen: AtomicU64,
    /// Per-device per-track consecutive playback failure records (see
    /// record_playback_failure). Tracked per-track so interleaved failures from
    /// the current and ENQUEUE'd next track don't reset each other's count.
    playback_failures: Mutex<HashMap<String, HashMap<String, FailureRecord>>>,
    /// Bumped when the sleep timer is set/cancelled; the spawned timer task
    /// checks this to know if it's been superseded.
    sleep_timer_gen: AtomicU64,
}

impl AppState {
    pub async fn new(
        api_token: Option<String>,
        redis_url: &str,
        locale: String,
    ) -> Result<Arc<Self>, Box<dyn std::error::Error>> {
        let (tx, _) = broadcast::channel::<String>(256);
        let cache_dir = std::env::current_dir()
            .unwrap_or_default()
            .join("audio_cache");
        std::fs::create_dir_all(&cache_dir).ok();

        let client = redis::Client::open(redis_url)?;
        let redis = time::timeout(time::Duration::from_secs(5), ConnectionManager::new(client))
            .await
            .map_err(|_| format!("Redis connection timed out ({redis_url})"))??;

        Ok(Arc::new(Self {
            redis,
            tx,
            cache_dir,
            api_token,
            locale,
            restoring: AtomicBool::new(false),
            order_lock: Mutex::new(()),
            extract_locks: Mutex::new(HashMap::new()),
            downloads: Mutex::new(HashMap::new()),
            import_cancel_gen: AtomicU64::new(0),
            playback_failures: Mutex::new(HashMap::new()),
            sleep_timer_gen: AtomicU64::new(0),
        }))
    }

    // ── Audio extraction ──

    pub async fn extract_audio(self: &Arc<Self>, url: &str) -> Result<AudioTrack, String> {
        let video_id = extract_video_id(url).ok_or("Could not recognize YouTube URL")?;

        // Serialize concurrent requests for the same video. Subsequent callers
        // hit the cache check after acquiring the lock and return immediately.
        let lock = {
            let mut locks = self.extract_locks.lock().await;
            locks.entry(video_id.clone()).or_default().clone()
        };
        let guard = lock.lock().await;
        let result = self.extract_audio_locked(&video_id, url).await;
        drop(guard);

        // Clean up the entry if no other callers are waiting (2 = map + self).
        let mut locks = self.extract_locks.lock().await;
        if locks
            .get(&video_id)
            .is_some_and(|l| Arc::strong_count(l) <= 2)
        {
            locks.remove(&video_id);
        }

        result
    }

    async fn extract_audio_locked(
        self: &Arc<Self>,
        video_id: &str,
        url: &str,
    ) -> Result<AudioTrack, String> {
        // Redis cache check. Entries pointing to old formats (mp3 etc.) are
        // stale w.r.t. AUDIO_MIME, so skip them and re-fetch.
        if let Some(track) = self.get_track(video_id).await {
            if track.is_live {
                tracing::info!("Cache hit (live): {}", video_id);
                return Ok(track);
            }
            let path = Path::new(&track.file_path);
            if path.extension().is_some_and(|ext| ext == AUDIO_EXT) && path.exists() {
                tracing::info!("Cache hit: {}", video_id);
                return Ok(track);
            }
        }

        // Fetch while broadcasting progress to all clients. Remove on success;
        // keep as error display for a while on failure.
        self.begin_download(video_id).await;
        let result = self.fetch_and_register(video_id, url).await;
        match &result {
            Ok(_) => self.finish_download(video_id).await,
            Err(e) => self.fail_download(video_id, e).await,
        }
        result
    }

    /// Fetch metadata → download (non-live) → register in Redis.
    /// Progress is reflected in the downloads progress entry.
    async fn fetch_and_register(&self, video_id: &str, url: &str) -> Result<AudioTrack, String> {
        // Fetch metadata
        tracing::info!("Fetching metadata: {}", video_id);
        let meta = fetch_metadata(url).await?;
        let title = meta["title"].as_str().unwrap_or(video_id).to_string();
        let is_live = meta["is_live"].as_bool().unwrap_or(false);
        self.set_download_meta(video_id, &title, is_live).await;

        // Live streams cannot be saved as files; register metadata only and
        // resolve the CDN URL at playback time (handlers::live_audio).
        let track = if is_live {
            tracing::info!("Live stream detected, skipping download: {}", video_id);
            AudioTrack::from_meta(video_id, &meta, now_f64(), String::new())
        } else {
            let output_path = self.cache_dir.join(format!("{video_id}.{AUDIO_EXT}"));
            let output_str = output_path.to_string_lossy().to_string();

            // Download audio
            tracing::info!("Downloading: {}", title);
            if let Err(e) = self.run_download(video_id, url, &output_str).await {
                // With --no-part, partial files remain under the final name.
                // Remove them so they don't get registered as broken tracks on restore.
                let _ = tokio::fs::remove_file(&output_path).await;
                return Err(e);
            }

            AudioTrack::from_meta(video_id, &meta, now_f64(), output_str)
        };

        let mut conn = self.redis.clone();
        let _: Result<(), _> = conn
            .hset(REDIS_KEY_TRACKS, video_id, track.to_redis_json())
            .await;
        // Prepend to the order list (remove first to avoid duplicates on re-fetch)
        {
            let _guard = self.order_lock.lock().await;
            let _: Result<(), _> = conn.lrem(REDIS_KEY_TRACKS_ORDER, 0, video_id).await;
            let _: Result<(), _> = conn.lpush(REDIS_KEY_TRACKS_ORDER, video_id).await;
        }

        tracing::info!("Ready: {} ({}s)", track.title, track.duration);
        Ok(track)
    }

    /// Download audio with yt-dlp. Read progress lines from stdout and
    /// update the download progress entry with the percentage until done.
    async fn run_download(
        &self,
        video_id: &str,
        url: &str,
        output_str: &str,
    ) -> Result<(), String> {
        // Prefer AAC source so no re-encode is needed for AUDIO_EXT (remux only)
        let format_spec = format!("bestaudio[ext={AUDIO_EXT}]/bestaudio");
        // Have yt-dlp emit progress in a machine-readable one-line-per-update format
        let progress_template = format!("download:{PROGRESS_PREFIX}%(progress._percent_str)s");
        let mut child = Command::new("yt-dlp")
            .args([
                "-f",
                &format_spec,
                "-x",
                "--audio-format",
                AUDIO_EXT,
                "-o",
                output_str,
                "--no-playlist",
                "--no-part",
                "--newline",
                "--progress-template",
                &progress_template,
                url,
            ])
            .stdin(Stdio::null())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .map_err(|e| format!("Download error: {e}"))?;

        // Drain stderr in a separate task to prevent pipe-full blocking;
        // its content is only used for error messages.
        let stderr = child.stderr.take();
        let stderr_task = tokio::spawn(async move {
            let mut buf = Vec::new();
            if let Some(mut stderr) = stderr {
                let _ = stderr.read_to_end(&mut buf).await;
            }
            buf
        });

        // Read progress lines as raw bytes with lossy conversion. lines() would
        // error on non-UTF-8, stopping the reader and closing the pipe, which
        // causes yt-dlp to die with EPIPE.
        if let Some(stdout) = child.stdout.take() {
            let mut reader = BufReader::new(stdout);
            let mut buf = Vec::new();
            loop {
                buf.clear();
                match reader.read_until(b'\n', &mut buf).await {
                    Ok(0) | Err(_) => break,
                    Ok(_) => {
                        let line = String::from_utf8_lossy(&buf);
                        if let Some(percent) = parse_progress_percent(line.trim_end()) {
                            self.set_download_percent(video_id, percent).await;
                        }
                    }
                }
            }
        }

        let status = child
            .wait()
            .await
            .map_err(|e| format!("Download error: {e}"))?;
        if !status.success() {
            let stderr_buf = stderr_task.await.unwrap_or_default();
            return Err(format!(
                "Failed to download audio: {}",
                snippet(&String::from_utf8_lossy(&stderr_buf))
            ));
        }
        Ok(())
    }

    // ── Download progress ──

    /// Mutate the download progress map and broadcast if changed.
    /// `f` returns whether a notification-worthy change was made. The payload
    /// is built while holding the lock to avoid drift between state and broadcast.
    async fn update_downloads(
        &self,
        f: impl FnOnce(&mut HashMap<String, DownloadProgress>) -> bool,
    ) {
        let payload = {
            let mut downloads = self.downloads.lock().await;
            if !f(&mut downloads) {
                return;
            }
            Self::downloads_payload(&downloads)
        };
        self.broadcast(json!({ "type": "downloads_update", "downloads": payload }));
    }

    /// Mutate a single download entry (no-op if not found).
    /// `f` returns whether a notification-worthy change was made.
    async fn update_download(&self, video_id: &str, f: impl FnOnce(&mut DownloadProgress) -> bool) {
        self.update_downloads(|downloads| downloads.get_mut(video_id).is_some_and(f))
            .await;
    }

    /// Register a download in the progress map and broadcast (shows video ID until title is known).
    async fn begin_download(&self, video_id: &str) {
        self.update_downloads(|downloads| {
            downloads.insert(
                video_id.to_string(),
                DownloadProgress {
                    id: video_id.to_string(),
                    title: video_id.to_string(),
                    status: DownloadStatus::Metadata,
                    percent: 0.0,
                    error: None,
                    started_at: now_f64(),
                },
            );
            true
        })
        .await;
    }

    /// Set the title after metadata fetch. Live streams are not downloaded
    /// (they leave the list immediately on registration), so advance status only for non-live.
    async fn set_download_meta(&self, video_id: &str, title: &str, is_live: bool) {
        self.update_download(video_id, |d| {
            d.title = title.to_string();
            if !is_live {
                d.status = DownloadStatus::Downloading;
            }
            true
        })
        .await;
    }

    /// Update download percentage. yt-dlp emits progress lines at high frequency,
    /// so only broadcast when the integer part changes. At 100%, mark as processing
    /// (yt-dlp post-processing).
    async fn set_download_percent(&self, video_id: &str, percent: f64) {
        self.update_download(video_id, |d| {
            let before = d.percent as u64;
            d.percent = percent.clamp(0.0, 100.0);
            if d.percent >= 100.0 {
                d.status = DownloadStatus::Processing;
            }
            d.percent as u64 != before
        })
        .await;
    }

    /// Remove a finished download from the progress map and broadcast.
    async fn finish_download(&self, video_id: &str) {
        self.update_downloads(|downloads| downloads.remove(video_id).is_some())
            .await;
    }

    /// Switch a failed download entry to error display, then clean it up after TTL.
    async fn fail_download(self: &Arc<Self>, video_id: &str, error: &str) {
        let mut started_at = None;
        self.update_download(video_id, |d| {
            d.status = DownloadStatus::Error;
            d.error = Some(error.to_string());
            started_at = Some(d.started_at);
            true
        })
        .await;
        let Some(started_at) = started_at else {
            return;
        };

        let state = self.clone();
        let video_id = video_id.to_string();
        tokio::spawn(async move {
            time::sleep(time::Duration::from_secs(DOWNLOAD_ERROR_TTL_SECS)).await;
            state
                .update_downloads(|downloads| {
                    // Don't remove a newer entry created by a retry (identified by started_at)
                    match downloads.get(&video_id) {
                        Some(d) if d.started_at == started_at => {
                            downloads.remove(&video_id).is_some()
                        }
                        _ => false,
                    }
                })
                .await;
        });
    }

    /// Cancel all in-progress downloads and clear the progress display.
    /// A running playlist import will stop after the current video finishes.
    pub async fn cancel_downloads(&self) {
        self.import_cancel_gen.fetch_add(1, Ordering::Relaxed);
        self.update_downloads(|downloads| {
            if downloads.is_empty() {
                return false;
            }
            downloads.clear();
            true
        })
        .await;
    }

    /// Return in-progress downloads sorted by start time (wire format for init / downloads_update).
    pub async fn downloads_json(&self) -> Value {
        Self::downloads_payload(&*self.downloads.lock().await)
    }

    fn downloads_payload(downloads: &HashMap<String, DownloadProgress>) -> Value {
        let mut list: Vec<&DownloadProgress> = downloads.values().collect();
        list.sort_by(|a, b| a.started_at.total_cmp(&b.started_at));
        json!(list)
    }

    pub async fn get_track(&self, id: &str) -> Option<AudioTrack> {
        self.try_get_track(id).await.ok().flatten()
    }

    /// Get a track, distinguishing Redis errors (Err) from not-found (Ok(None)).
    /// Callers that need to decide "safe to delete if missing" should use this.
    /// Unparsable entries are treated as not-found.
    async fn try_get_track(&self, id: &str) -> redis::RedisResult<Option<AudioTrack>> {
        let mut conn = self.redis.clone();
        let json_str: Option<String> = conn.hget(REDIS_KEY_TRACKS, id).await?;
        Ok(json_str.and_then(|s| AudioTrack::from_redis_json(&s)))
    }

    pub async fn remove_track(&self, id: &str) -> Option<AudioTrack> {
        let track = self.get_track(id).await?;

        // Delete the file first. If removing the last track causes the tracks key
        // to vanish, restore_tracks_if_missing may run — and if the file still
        // exists, the deleted track would be resurrected.
        if !track.file_path.is_empty() {
            let _ = tokio::fs::remove_file(&track.file_path).await;
        }

        let mut conn = self.redis.clone();
        let _: Result<(), _> = conn.hdel(REDIS_KEY_TRACKS, id).await;
        {
            // Serialize with reorder's read-then-replace to prevent a deletion
            // from being silently undone by a concurrent reorder write-back.
            let _guard = self.order_lock.lock().await;
            let _: Result<(), _> = conn.lrem(REDIS_KEY_TRACKS_ORDER, 0, id).await;

            // Remove from all playlist track lists in a single pipeline round-trip
            let playlists = self.playlists().await;
            if !playlists.is_empty() {
                let mut pipe = redis::pipe();
                for playlist in &playlists {
                    pipe.lrem(playlist_key(&playlist.id), 0, id).ignore();
                }
                if let Err(e) = pipe.query_async::<()>(&mut conn).await {
                    tracing::warn!("Redis error removing track {id} from playlists: {e}");
                }
            }
        }

        // Remove pending commands that reference the deleted track
        let pattern = format!("{REDIS_PENDING_PREFIX}:*");
        let keys: Vec<String> = match conn.scan_match::<_, String>(&pattern).await {
            Ok(mut iter) => {
                let mut keys = Vec::new();
                while let Some(key) = iter.next_item().await {
                    match key {
                        Ok(key) => keys.push(key),
                        Err(e) => {
                            tracing::warn!("Redis error scanning pending commands: {e}");
                            break;
                        }
                    }
                }
                keys
            }
            Err(e) => {
                tracing::warn!("Redis error scanning pending commands: {e}");
                Vec::new()
            }
        };
        for key in keys {
            let json_str: Option<String> = conn.get(&key).await.unwrap_or_default();
            if json_str
                .and_then(|s| serde_json::from_str::<PendingCommand>(&s).ok())
                .is_some_and(|cmd| cmd.track.id == id)
            {
                let _: Result<(), _> = conn.del(&key).await;
            }
        }

        for mut dev in self.all_devices().await.into_values() {
            // Also remove the deleted track from each device's Up Next queue
            let key = queue_key(&dev.device_id);
            let entries: Vec<String> = conn.lrange(&key, 0, -1).await.unwrap_or_default();
            for entry in entries.iter().filter(|e| token_track_id(e) == id) {
                let _: Result<(), _> = conn.lrem(&key, 0, entry).await;
            }
            if dev.current_track.as_ref().is_some_and(|t| t.id == id) {
                dev.current_track = None;
                dev.status = "idle".to_string();
                self.write_device(&dev).await;
            }
        }

        Some(track)
    }

    /// Return all tracks in saved order. Tracks not in the order list
    /// (pre-reorder data or freshly restored) are appended newest-first.
    pub async fn list_tracks(&self) -> Vec<AudioTrack> {
        let mut conn = self.redis.clone();
        let all: HashMap<String, String> = conn.hgetall(REDIS_KEY_TRACKS).await.unwrap_or_default();
        let mut by_id: HashMap<String, AudioTrack> = all
            .values()
            .filter_map(|s| AudioTrack::from_redis_json(s))
            .map(|t| (t.id.clone(), t))
            .collect();

        let order: Vec<String> = conn
            .lrange(REDIS_KEY_TRACKS_ORDER, 0, -1)
            .await
            .unwrap_or_else(|e| {
                tracing::warn!("Redis error reading track order: {e}");
                Vec::new()
            });
        let mut tracks: Vec<AudioTrack> = order.iter().filter_map(|id| by_id.remove(id)).collect();

        let mut rest: Vec<AudioTrack> = by_id.into_values().collect();
        rest.sort_by(|a, b| {
            b.created_at
                .partial_cmp(&a.created_at)
                .unwrap_or(std::cmp::Ordering::Equal)
                .then_with(|| a.id.cmp(&b.id))
        });
        tracks.extend(rest);
        tracks
    }

    /// Move a track to new_index (0-based) and persist. If playlist_id is given,
    /// reorder within that playlist; otherwise reorder the entire library.
    pub async fn reorder_track(
        &self,
        playlist_id: Option<&str>,
        track_id: &str,
        new_index: usize,
    ) -> ReorderOutcome {
        // Serialize to prevent interleaving changes between read and full replace
        let _guard = self.order_lock.lock().await;
        let (key, mut ids) = match playlist_id {
            Some(pid) => (playlist_key(pid), self.playlist_track_ids(pid).await),
            None => (
                REDIS_KEY_TRACKS_ORDER.to_string(),
                self.list_tracks().await.into_iter().map(|t| t.id).collect(),
            ),
        };
        let Some(pos) = ids.iter().position(|id| id == track_id) else {
            return ReorderOutcome::NotInList;
        };
        let id = ids.remove(pos);
        ids.insert(new_index.min(ids.len()), id);

        // Rewrite the entire order list (at most a few hundred items, so full replace is fine)
        let mut pipe = redis::pipe();
        pipe.atomic().del(&key).rpush(&key, &ids);
        let mut conn = self.redis.clone();
        match pipe.query_async::<()>(&mut conn).await {
            Ok(()) => ReorderOutcome::Moved,
            Err(e) => {
                tracing::warn!("Redis error writing track order: {e}");
                ReorderOutcome::Failed
            }
        }
    }

    /// If the youtube:tracks key is missing in Redis (e.g. after a fresh init),
    /// re-fetch metadata from audio_cache m4a filenames and register them.
    /// Since yt-dlp takes time per track, restoration runs in the background
    /// and broadcasts tracks_update on completion so clients refresh.
    pub async fn restore_tracks_if_missing(self: &Arc<Self>) {
        let mut conn = self.redis.clone();
        match conn.exists::<_, bool>(REDIS_KEY_TRACKS).await {
            Ok(false) => {}
            Ok(true) => return,
            Err(e) => {
                tracing::warn!("Redis error checking tracks key: {e}");
                return;
            }
        }

        let cached = cached_video_ids(&self.cache_dir);
        if cached.is_empty() {
            return;
        }

        if self
            .restoring
            .compare_exchange(false, true, Ordering::SeqCst, Ordering::SeqCst)
            .is_err()
        {
            return;
        }

        let state = self.clone();
        tokio::spawn(async move {
            tracing::info!(
                "Tracks key missing: restoring {} track(s) from audio_cache",
                cached.len()
            );
            for (video_id, path) in cached {
                let track = state.refetch_track_metadata(&video_id, &path).await;
                let mut conn = state.redis.clone();
                if let Err(e) = conn
                    .hset::<_, _, _, ()>(REDIS_KEY_TRACKS, &video_id, track.to_redis_json())
                    .await
                {
                    tracing::warn!("Redis error restoring track {video_id}: {e}");
                }
            }
            state.broadcast_tracks().await;
            state.restoring.store(false, Ordering::SeqCst);
            tracing::info!("Track restore finished");
        });
    }

    /// Re-fetch metadata only via yt-dlp. If the video is deleted or unavailable,
    /// the file can still be played, so return minimal info with the ID as title.
    async fn refetch_track_metadata(&self, video_id: &str, path: &Path) -> AudioTrack {
        let url = format!("https://www.youtube.com/watch?v={video_id}");
        let meta = match fetch_metadata(&url).await {
            Ok(meta) => meta,
            Err(e) => {
                tracing::warn!("Metadata refetch failed for {video_id}: {e}");
                Value::Null
            }
        };

        // Use the original file's mtime as created_at to preserve registration order
        AudioTrack::from_meta(
            video_id,
            &meta,
            file_mtime_f64(path),
            path.to_string_lossy().to_string(),
        )
    }

    /// Return tracks for the given scope. If a playlist is specified, return its
    /// track order; otherwise return the full library order.
    pub async fn scoped_tracks(&self, playlist_id: Option<&str>) -> Vec<AudioTrack> {
        match playlist_id {
            Some(pid) => self.list_playlist_tracks(pid).await,
            None => self.list_tracks().await,
        }
    }

    /// Return tracks in the active scope (active playlist, or entire library if none).
    async fn active_scope_tracks(&self) -> Vec<AudioTrack> {
        let scope = self.active_playlist().await;
        self.scoped_tracks(scope.as_deref()).await
    }

    /// Return the next track to play after the current one ends, based on the
    /// playback mode ("off" returns None). Selection uses the active playlist scope.
    pub async fn auto_next_track(&self, current_id: &str) -> Option<AudioTrack> {
        match self.playback_mode().await.as_str() {
            "loop" => neighbor_track(&self.active_scope_tracks().await, current_id, 1),
            "shuffle" => random_track_from(self.active_scope_tracks().await, current_id),
            _ => None, // "off": no auto-play
        }
    }

    /// Return the track to play on an explicit "next" command. Shuffle picks
    /// randomly; otherwise advance in order (even when mode is "off").
    pub async fn skip_next_track(&self, current_id: &str) -> Option<AudioTrack> {
        if self.playback_mode().await == "shuffle" {
            random_track_from(self.active_scope_tracks().await, current_id)
        } else {
            neighbor_track(&self.active_scope_tracks().await, current_id, 1)
        }
    }

    /// Return the track to play on an explicit "previous" command (wraps from first to last).
    pub async fn skip_prev_track(&self, current_id: &str) -> Option<AudioTrack> {
        neighbor_track(&self.active_scope_tracks().await, current_id, -1)
    }

    /// Return tracks for the given page (1-based) and total count.
    /// If playlist_id is given, return in that playlist's track order.
    /// If filter is given, only include tracks whose title or channel
    /// contains the substring (case-insensitive).
    pub async fn list_tracks_page(
        &self,
        playlist_id: Option<&str>,
        page: usize,
        per_page: usize,
        filter: Option<&str>,
    ) -> (Vec<AudioTrack>, usize) {
        let tracks = self.scoped_tracks(playlist_id).await;
        let tracks = match filter {
            Some(q) => {
                let q = q.to_lowercase();
                tracks
                    .into_iter()
                    .filter(|t| {
                        t.title.to_lowercase().contains(&q) || t.channel.to_lowercase().contains(&q)
                    })
                    .collect()
            }
            None => tracks,
        };
        let total = tracks.len();
        let start = page.saturating_sub(1).saturating_mul(per_page);
        let items = tracks.into_iter().skip(start).take(per_page).collect();
        (items, total)
    }

    // ── Device management ──

    async fn write_device(&self, dev: &DeviceState) {
        let json_str = match serde_json::to_string(dev) {
            Ok(s) => s,
            Err(e) => {
                tracing::warn!("Failed to serialize device {}: {e}", dev.device_id);
                return;
            }
        };
        let mut conn = self.redis.clone();
        if let Err(e) = conn
            .hset::<_, _, _, ()>(REDIS_KEY_DEVICES, &dev.device_id, json_str)
            .await
        {
            tracing::warn!("Redis error writing device {}: {e}", dev.device_id);
        }
    }

    pub async fn get_device(&self, device_id: &str) -> Option<DeviceState> {
        let mut conn = self.redis.clone();
        match conn
            .hget::<_, _, Option<String>>(REDIS_KEY_DEVICES, device_id)
            .await
        {
            Ok(Some(s)) => serde_json::from_str(&s).ok(),
            Ok(None) => None,
            Err(e) => {
                tracing::warn!("Redis error reading device {device_id}: {e}");
                None
            }
        }
    }

    async fn all_devices(&self) -> HashMap<String, DeviceState> {
        let mut conn = self.redis.clone();
        let all: HashMap<String, String> =
            conn.hgetall(REDIS_KEY_DEVICES).await.unwrap_or_else(|e| {
                tracing::warn!("Redis error listing devices: {e}");
                HashMap::new()
            });
        all.into_iter()
            .filter_map(|(k, s)| serde_json::from_str(&s).ok().map(|d| (k, d)))
            .collect()
    }

    pub async fn device_ids(&self) -> redis::RedisResult<Vec<String>> {
        let mut conn = self.redis.clone();
        conn.hkeys(REDIS_KEY_DEVICES).await
    }

    pub async fn register_device(&self, device_id: &str, name: &str) -> DeviceState {
        let now = now_f64();
        let mut dev = self
            .get_device(device_id)
            .await
            .unwrap_or_else(|| DeviceState {
                device_id: device_id.to_string(),
                name: name.to_string(),
                status: "idle".to_string(),
                current_track: None,
                position_ms: 0,
                connected: true,
                last_update: now,
            });
        dev.connected = true;
        dev.apply(DeviceUpdate::new(), now);
        self.write_device(&dev).await;
        dev
    }

    pub async fn update_device(&self, device_id: &str, upd: DeviceUpdate) {
        let Some(mut dev) = self.get_device(device_id).await else {
            return;
        };
        dev.apply(upd, now_f64());
        self.write_device(&dev).await;
    }

    /// Record the actual stop position. If still "playing", transition to "paused".
    /// Does not overwrite "paused"/"stopped" already set by a Pause/Stop intent.
    pub async fn pause_if_playing(&self, device_id: &str, offset_ms: u64) {
        let Some(mut dev) = self.get_device(device_id).await else {
            return;
        };
        let mut upd = DeviceUpdate::new().position(offset_ms);
        if dev.status == "playing" {
            upd = upd.status("paused");
        }
        dev.apply(upd, now_f64());
        self.write_device(&dev).await;
    }

    pub async fn remove_device(&self, device_id: &str) -> Option<DeviceState> {
        let device = self.get_device(device_id).await?;
        let mut conn = self.redis.clone();
        let _: Result<(), _> = conn.hdel(REDIS_KEY_DEVICES, device_id).await;
        let _: Result<(), _> = conn.del(pending_key(device_id)).await;
        let _: Result<(), _> = conn.del(queue_key(device_id)).await;
        self.clear_playback_failures(device_id).await;
        Some(device)
    }

    /// Record a playback failure with its position and return the consecutive
    /// failure count for this track (including the current one).
    pub async fn record_playback_failure(
        &self,
        device_id: &str,
        track_id: &str,
        offset_ms: u64,
    ) -> u32 {
        self.playback_failures
            .lock()
            .await
            .entry(device_id.to_string())
            .or_default()
            .entry(track_id.to_string())
            .or_default()
            .record(offset_ms, now_f64())
    }

    /// Discard a device's failure records (next failure starts counting from 1).
    pub async fn clear_playback_failures(&self, device_id: &str) {
        self.playback_failures.lock().await.remove(device_id);
    }

    /// Return device states with their Up Next queues attached. Queue track
    /// references are resolved in a single HMGET across all devices to minimize
    /// round-trips (called from every Alexa webhook response path).
    pub async fn devices_json(&self) -> Value {
        let devices = self.all_devices().await;

        let mut queues: HashMap<String, Vec<String>> = HashMap::new();
        for id in devices.keys() {
            queues.insert(id.clone(), self.queue_entries(id).await);
        }
        let tracks = self.fetch_tracks_for(queues.values().flatten()).await;

        let mut map = serde_json::Map::new();
        for (id, dev) in devices {
            let queue: Vec<QueueItem> = queues
                .remove(&id)
                .unwrap_or_default()
                .into_iter()
                // Hide entries whose referenced track is gone (peek_queue cleans them up later)
                .filter_map(|entry| {
                    let track = tracks.get(token_track_id(&entry)).cloned()?;
                    Some(QueueItem { entry, track })
                })
                .collect();
            match serde_json::to_value(DeviceJson { device: dev, queue }) {
                Ok(v) => {
                    map.insert(id, v);
                }
                Err(e) => tracing::warn!("Failed to serialize device {id}: {e}"),
            }
        }
        Value::Object(map)
    }

    /// Fetch tracks referenced by queue entries in a single HMGET.
    async fn fetch_tracks_for(
        &self,
        entries: impl Iterator<Item = &String>,
    ) -> HashMap<String, AudioTrack> {
        let mut ids: Vec<&str> = entries.map(|e| token_track_id(e)).collect();
        ids.sort_unstable();
        ids.dedup();
        if ids.is_empty() {
            return HashMap::new();
        }

        let mut conn = self.redis.clone();
        let vals: Vec<Option<String>> = match conn.hmget(REDIS_KEY_TRACKS, &ids).await {
            Ok(vals) => vals,
            Err(e) => {
                tracing::warn!("Redis error resolving queue tracks: {e}");
                return HashMap::new();
            }
        };
        ids.into_iter()
            .zip(vals)
            .filter_map(|(id, v)| {
                let track = v.and_then(|s| AudioTrack::from_redis_json(&s))?;
                Some((id.to_string(), track))
            })
            .collect()
    }

    // ── Broadcast ──

    /// Send a message to all connected WebSocket clients (no-op if no subscribers).
    fn broadcast(&self, msg: Value) {
        let _ = self.tx.send(msg.to_string());
    }

    pub async fn broadcast_devices(&self) {
        self.broadcast(json!({
            "type": "device_update",
            "devices": self.devices_json().await,
        }));
    }

    /// Notify clients that the track list changed (content is re-fetched via REST).
    pub async fn broadcast_tracks(&self) {
        self.broadcast(json!({ "type": "tracks_update" }));
    }

    /// Broadcast playlist list/content changes to all clients.
    pub async fn broadcast_playlists(&self) {
        self.broadcast(json!({
            "type": "playlists_update",
            "playlists": self.playlists_json().await,
        }));
    }

    /// Broadcast active playlist (selection scope) changes to all clients.
    pub async fn broadcast_active_playlist(&self) {
        self.broadcast(json!({
            "type": "active_playlist_update",
            "playlist": self.active_playlist().await,
        }));
    }

    // ── Playback mode ──

    /// Return the saved playback mode (invalid/missing values are normalized to
    /// the default; Redis errors are returned as Err for the caller to decide).
    async fn try_playback_mode(&self) -> redis::RedisResult<String> {
        let mut conn = self.redis.clone();
        let mode: Option<String> = conn.get(REDIS_KEY_PLAYBACK_MODE).await?;
        Ok(mode
            .filter(|m| PLAYBACK_MODES.contains(&m.as_str()))
            .unwrap_or_else(|| DEFAULT_PLAYBACK_MODE.to_string()))
    }

    /// Return the playback mode (end-of-track behavior). Falls back to default on Redis error.
    pub async fn playback_mode(&self) -> String {
        self.try_playback_mode().await.unwrap_or_else(|e| {
            tracing::warn!("Redis error reading playback mode: {e}");
            DEFAULT_PLAYBACK_MODE.to_string()
        })
    }

    /// Return true only when the mode is confirmed to be "off". Used to decide
    /// whether to stop ongoing playback, so on Redis error it falls back to
    /// false (don't stop) — since the default is "off", playback_mode() alone
    /// can't distinguish a transient error from a genuine "off".
    pub async fn playback_mode_is_off(&self) -> bool {
        match self.try_playback_mode().await {
            Ok(mode) => mode == "off",
            Err(e) => {
                tracing::warn!("Redis error reading playback mode: {e}");
                false
            }
        }
    }

    /// Save the playback mode. Returns false for unknown values or Redis errors.
    pub async fn set_playback_mode(&self, mode: &str) -> bool {
        if !PLAYBACK_MODES.contains(&mode) {
            return false;
        }
        let mut conn = self.redis.clone();
        match conn.set::<_, _, ()>(REDIS_KEY_PLAYBACK_MODE, mode).await {
            Ok(()) => true,
            Err(e) => {
                tracing::warn!("Redis error writing playback mode: {e}");
                false
            }
        }
    }

    // ── Sleep timer ──

    /// Return the sleep timer expiry as UNIX seconds, or None if not set / expired.
    pub async fn sleep_timer(&self) -> Option<f64> {
        let mut conn = self.redis.clone();
        let expiry: Option<f64> = match conn.get(REDIS_KEY_SLEEP_TIMER).await {
            Ok(v) => v,
            Err(e) => {
                tracing::warn!("Redis error reading sleep timer: {e}");
                return None;
            }
        };
        expiry.filter(|&t| t > now_f64())
    }

    /// Set a sleep timer that fires after `minutes` minutes. Spawns a task that
    /// stops all devices and sets playback mode to "off" when it expires.
    /// Returns the expiry time (UNIX seconds).
    pub async fn set_sleep_timer(self: &Arc<Self>, minutes: u64) -> f64 {
        let generation = self.sleep_timer_gen.fetch_add(1, Ordering::Relaxed) + 1;
        let expiry = now_f64() + (minutes as f64) * 60.0;

        let mut conn = self.redis.clone();
        let ttl_secs = (minutes * 60) + 10;
        let _: Result<(), _> = conn
            .set_ex::<_, _, ()>(REDIS_KEY_SLEEP_TIMER, expiry, ttl_secs)
            .await;

        self.spawn_sleep_expiry(time::Duration::from_secs(minutes * 60), generation);
        expiry
    }

    /// Re-spawn the sleep timer task after a server restart. If a timer is
    /// still active in Redis, calculate the remaining time and schedule the
    /// expiry task so the timer actually fires.
    pub async fn restore_sleep_timer(self: &Arc<Self>) {
        let Some(expiry) = self.sleep_timer().await else {
            return;
        };
        let remaining_secs = expiry - now_f64();
        if remaining_secs <= 0.0 {
            self.cancel_sleep_timer().await;
            return;
        }
        let generation = self.sleep_timer_gen.load(Ordering::Relaxed);
        self.spawn_sleep_expiry(time::Duration::from_secs_f64(remaining_secs), generation);
        tracing::info!("Restored sleep timer ({remaining_secs:.0}s remaining)");
    }

    fn spawn_sleep_expiry(self: &Arc<Self>, delay: time::Duration, generation: u64) {
        let state = self.clone();
        tokio::spawn(async move {
            time::sleep(delay).await;
            if state.sleep_timer_gen.load(Ordering::Relaxed) != generation {
                return;
            }
            tracing::info!("Sleep timer expired, stopping all devices");
            let mut conn = state.redis.clone();
            let _: Result<(), _> = conn.del::<_, ()>(REDIS_KEY_SLEEP_TIMER).await;
            state.set_playback_mode("off").await;
            state.broadcast_playback_mode("off").await;
            let device_ids = state.device_ids().await.unwrap_or_default();
            for did in &device_ids {
                state
                    .update_device(did, DeviceUpdate::new().status("stopped"))
                    .await;
            }
            state.broadcast_devices().await;
            state.broadcast_sleep_timer().await;
        });
    }

    /// Cancel the sleep timer.
    pub async fn cancel_sleep_timer(&self) {
        self.sleep_timer_gen.fetch_add(1, Ordering::Relaxed);
        let mut conn = self.redis.clone();
        let _: Result<(), _> = conn.del::<_, ()>(REDIS_KEY_SLEEP_TIMER).await;
    }

    pub async fn broadcast_sleep_timer(&self) {
        self.broadcast(json!({
            "type": "sleep_timer_update",
            "expires_at": self.sleep_timer().await,
        }));
    }

    pub async fn broadcast_playback_mode(&self, mode: &str) {
        self.broadcast(json!({
            "type": "playback_mode_update",
            "mode": mode,
        }));
    }

    // ── Command queue ──

    pub async fn queue_play(&self, device_id: &str, track: AudioTrack, offset_ms: u64) {
        // Explicit play command from the web UI — reset consecutive failure
        // records to allow retries.
        self.clear_playback_failures(device_id).await;
        let cmd = PendingCommand {
            action: "play".to_string(),
            track: track.clone(),
            offset_ms,
        };
        let Ok(json_str) = serde_json::to_string(&cmd) else {
            return;
        };
        let mut conn = self.redis.clone();
        if let Err(e) = conn
            .set_ex::<_, _, ()>(pending_key(device_id), json_str, PENDING_TTL_SECS)
            .await
        {
            // Don't show "queued" status if the command couldn't be saved
            tracing::warn!("Redis error queueing play for {device_id}: {e}");
            return;
        }
        // Align position to the queued start offset (used by Resume and the web UI)
        self.update_device(
            device_id,
            DeviceUpdate::new()
                .status("queued")
                .track(track)
                .position(offset_ms),
        )
        .await;
    }

    /// Consume a queued command (atomic get+delete via GETDEL; expiry is handled by Redis TTL).
    pub async fn take_pending(&self, device_id: &str) -> Option<PendingCommand> {
        let mut conn = self.redis.clone();
        let result = conn
            .get_del::<_, Option<String>>(pending_key(device_id))
            .await;
        Self::parse_pending(device_id, result)
    }

    /// Peek at a queued command without consuming it (use take_pending to consume).
    pub async fn peek_pending(&self, device_id: &str) -> Option<PendingCommand> {
        let mut conn = self.redis.clone();
        let result = conn.get::<_, Option<String>>(pending_key(device_id)).await;
        Self::parse_pending(device_id, result)
    }

    /// Discard a queued command.
    pub async fn clear_pending(&self, device_id: &str) {
        let mut conn = self.redis.clone();
        if let Err(e) = conn.del::<_, ()>(pending_key(device_id)).await {
            tracing::warn!("Redis error clearing pending for {device_id}: {e}");
        }
    }

    // ── Up Next queue ──

    /// Append a track to the device's Up Next queue. Returns false on Redis error.
    pub async fn push_queue(&self, device_id: &str, track_id: &str) -> bool {
        let mut conn = self.redis.clone();
        match conn
            .rpush::<_, _, ()>(queue_key(device_id), new_token(track_id))
            .await
        {
            Ok(()) => true,
            Err(e) => {
                tracing::warn!("Redis error pushing queue for {device_id}: {e}");
                false
            }
        }
    }

    /// Return a device's queue entries (track resolution is done by devices_json).
    async fn queue_entries(&self, device_id: &str) -> Vec<String> {
        let mut conn = self.redis.clone();
        conn.lrange(queue_key(device_id), 0, -1)
            .await
            .unwrap_or_else(|e| {
                tracing::warn!("Redis error reading queue for {device_id}: {e}");
                Vec::new()
            })
    }

    /// Peek at the front of the queue as (entry, track) without consuming.
    /// Entries whose referenced track is confirmed deleted are removed and the
    /// next entry is checked. On Redis error, fall back to None (don't remove).
    pub async fn peek_queue(&self, device_id: &str) -> Option<(String, AudioTrack)> {
        let mut conn = self.redis.clone();
        loop {
            let front: Option<String> = match conn.lindex(queue_key(device_id), 0).await {
                Ok(v) => v,
                Err(e) => {
                    tracing::warn!("Redis error reading queue for {device_id}: {e}");
                    return None;
                }
            };
            let entry = front?;
            match self.try_get_track(token_track_id(&entry)).await {
                Ok(Some(track)) => return Some((entry, track)),
                Ok(None) => {
                    // If removal failed, don't loop — retry on the next peek
                    if !self.remove_queue_entry(device_id, &entry).await {
                        return None;
                    }
                }
                Err(_) => return None,
            }
        }
    }

    /// Remove one entry by value (LREM). Returns false if not found. Entries are
    /// unique, so no index is needed and concurrent consumption doesn't conflict.
    pub async fn remove_queue_entry(&self, device_id: &str, entry: &str) -> bool {
        let mut conn = self.redis.clone();
        match conn.lrem::<_, _, i64>(queue_key(device_id), 1, entry).await {
            Ok(n) => n > 0,
            Err(e) => {
                tracing::warn!("Redis error removing queue entry for {device_id}: {e}");
                false
            }
        }
    }

    /// Clear the entire queue.
    pub async fn clear_queue(&self, device_id: &str) {
        let mut conn = self.redis.clone();
        if let Err(e) = conn.del::<_, ()>(queue_key(device_id)).await {
            tracing::warn!("Redis error clearing queue for {device_id}: {e}");
        }
    }

    // ── Playlists ──

    /// Create a playlist. Name is trimmed and must be 1–PLAYLIST_NAME_MAX_CHARS
    /// chars. Returns None for invalid names or Redis errors.
    pub async fn create_playlist(&self, name: &str) -> Option<Playlist> {
        let name = name.trim();
        if name.is_empty() || name.chars().count() > PLAYLIST_NAME_MAX_CHARS {
            return None;
        }
        let playlist = Playlist {
            id: new_playlist_id(),
            name: name.to_string(),
            created_at: now_f64(),
        };
        let json_str = serde_json::to_string(&playlist).expect("Playlist serializes to JSON");
        let mut conn = self.redis.clone();
        match conn
            .hset::<_, _, _, ()>(REDIS_KEY_PLAYLISTS, &playlist.id, json_str)
            .await
        {
            Ok(()) => Some(playlist),
            Err(e) => {
                tracing::warn!("Redis error creating playlist: {e}");
                None
            }
        }
    }

    /// Rename a playlist. Returns false if the name is invalid, the playlist
    /// doesn't exist, or Redis errors occur.
    pub async fn rename_playlist(&self, playlist_id: &str, name: &str) -> bool {
        let name = name.trim();
        if name.is_empty() || name.chars().count() > PLAYLIST_NAME_MAX_CHARS {
            return false;
        }
        let Some(mut playlist) = self.get_playlist(playlist_id).await else {
            return false;
        };
        playlist.name = name.to_string();
        let json_str = serde_json::to_string(&playlist).expect("Playlist serializes to JSON");
        let mut conn = self.redis.clone();
        match conn
            .hset::<_, _, _, ()>(REDIS_KEY_PLAYLISTS, playlist_id, json_str)
            .await
        {
            Ok(()) => true,
            Err(e) => {
                tracing::warn!("Redis error renaming playlist {playlist_id}: {e}");
                false
            }
        }
    }

    pub async fn get_playlist(&self, playlist_id: &str) -> Option<Playlist> {
        let mut conn = self.redis.clone();
        match conn
            .hget::<_, _, Option<String>>(REDIS_KEY_PLAYLISTS, playlist_id)
            .await
        {
            Ok(s) => s.and_then(|s| serde_json::from_str(&s).ok()),
            Err(e) => {
                tracing::warn!("Redis error reading playlist {playlist_id}: {e}");
                None
            }
        }
    }

    /// Return all playlists sorted by creation time.
    pub async fn playlists(&self) -> Vec<Playlist> {
        let mut conn = self.redis.clone();
        let all: HashMap<String, String> =
            conn.hgetall(REDIS_KEY_PLAYLISTS).await.unwrap_or_else(|e| {
                tracing::warn!("Redis error listing playlists: {e}");
                HashMap::new()
            });
        let mut playlists: Vec<Playlist> = all
            .values()
            .filter_map(|s| serde_json::from_str(s).ok())
            .collect();
        playlists.sort_by(|a, b| {
            a.created_at
                .total_cmp(&b.created_at)
                .then_with(|| a.id.cmp(&b.id))
        });
        playlists
    }

    /// Delete a playlist. Also removes its track list and clears the active playlist
    /// setting if it pointed here (tracks themselves are not deleted). Returns false if not found.
    pub async fn delete_playlist(&self, playlist_id: &str) -> bool {
        let mut conn = self.redis.clone();
        let removed: i64 = match conn.hdel(REDIS_KEY_PLAYLISTS, playlist_id).await {
            Ok(n) => n,
            Err(e) => {
                tracing::warn!("Redis error deleting playlist {playlist_id}: {e}");
                return false;
            }
        };
        if removed == 0 {
            return false;
        }
        let _: Result<(), _> = conn.del(playlist_key(playlist_id)).await;
        // If this was the active playlist, revert to the full library
        if self.raw_active_playlist().await.as_deref() == Some(playlist_id) {
            let _: Result<(), _> = conn.del(REDIS_KEY_ACTIVE_PLAYLIST).await;
        }
        true
    }

    /// Append a track to the end of a playlist (moves to end if already present).
    /// Returns false on Redis error.
    pub async fn add_playlist_track(&self, playlist_id: &str, track_id: &str) -> bool {
        // Remove first to avoid duplicates, then append. Serialized with
        // reorder's read-then-replace to prevent interleaving.
        let _guard = self.order_lock.lock().await;
        let key = playlist_key(playlist_id);
        let mut pipe = redis::pipe();
        pipe.atomic()
            .lrem(&key, 0, track_id)
            .ignore()
            .rpush(&key, track_id);
        let mut conn = self.redis.clone();
        match pipe.query_async::<()>(&mut conn).await {
            Ok(()) => true,
            Err(e) => {
                tracing::warn!("Redis error adding track to playlist {playlist_id}: {e}");
                false
            }
        }
    }

    /// Remove a track from a playlist. Returns false if not found.
    pub async fn remove_playlist_track(&self, playlist_id: &str, track_id: &str) -> bool {
        // Serialize with reorder's read-then-replace to prevent the removed
        // track from being restored by a concurrent write-back.
        let _guard = self.order_lock.lock().await;
        let mut conn = self.redis.clone();
        match conn
            .lrem::<_, _, i64>(playlist_key(playlist_id), 0, track_id)
            .await
        {
            Ok(n) => n > 0,
            Err(e) => {
                tracing::warn!("Redis error removing track from playlist {playlist_id}: {e}");
                false
            }
        }
    }

    async fn playlist_track_ids(&self, playlist_id: &str) -> Vec<String> {
        let mut conn = self.redis.clone();
        conn.lrange(playlist_key(playlist_id), 0, -1)
            .await
            .unwrap_or_else(|e| {
                tracing::warn!("Redis error reading playlist {playlist_id}: {e}");
                Vec::new()
            })
    }

    /// Return playlist tracks in playlist order (deleted tracks are skipped).
    pub async fn list_playlist_tracks(&self, playlist_id: &str) -> Vec<AudioTrack> {
        let ids = self.playlist_track_ids(playlist_id).await;
        let mut by_id = self.fetch_tracks_for(ids.iter()).await;
        ids.iter().filter_map(|id| by_id.remove(id)).collect()
    }

    /// Return all playlists with metadata and track counts in creation order (API/WS wire format).
    pub async fn playlists_json(&self) -> Value {
        let playlists = self.playlists().await;
        if playlists.is_empty() {
            return json!([]);
        }

        // Fetch track counts in a single pipeline round-trip
        let mut pipe = redis::pipe();
        for playlist in &playlists {
            pipe.llen(playlist_key(&playlist.id));
        }
        let mut conn = self.redis.clone();
        let counts: Vec<usize> = match pipe.query_async(&mut conn).await {
            Ok(counts) => counts,
            Err(e) => {
                tracing::warn!("Redis error reading playlist counts: {e}");
                vec![0; playlists.len()]
            }
        };

        let list: Vec<PlaylistJson> = playlists
            .into_iter()
            .zip(counts)
            .map(|(playlist, count)| PlaylistJson { playlist, count })
            .collect();
        json!(list)
    }

    /// Return the saved active playlist ID (no existence check).
    async fn raw_active_playlist(&self) -> Option<String> {
        let mut conn = self.redis.clone();
        match conn
            .get::<_, Option<String>>(REDIS_KEY_ACTIVE_PLAYLIST)
            .await
        {
            Ok(v) => v,
            Err(e) => {
                tracing::warn!("Redis error reading active playlist: {e}");
                None
            }
        }
    }

    /// Active playlist ID for loop/shuffle scope. Returns None (= full library)
    /// if unset or if the referenced playlist has been deleted.
    pub async fn active_playlist(&self) -> Option<String> {
        let id = self.raw_active_playlist().await?;
        if self.get_playlist(&id).await.is_some() {
            Some(id)
        } else {
            None
        }
    }

    /// Set the active playlist (None reverts to full library).
    /// Returns false for nonexistent playlists or Redis errors.
    pub async fn set_active_playlist(&self, playlist_id: Option<&str>) -> bool {
        let mut conn = self.redis.clone();
        let result = match playlist_id {
            Some(pid) => {
                if self.get_playlist(pid).await.is_none() {
                    return false;
                }
                conn.set::<_, _, ()>(REDIS_KEY_ACTIVE_PLAYLIST, pid).await
            }
            None => conn.del::<_, ()>(REDIS_KEY_ACTIVE_PLAYLIST).await,
        };
        match result {
            Ok(()) => true,
            Err(e) => {
                tracing::warn!("Redis error writing active playlist: {e}");
                false
            }
        }
    }

    /// Flat-expand a YouTube playlist and start importing into a local playlist
    /// with the same name (created if absent) in the background. Returns the
    /// playlist name and item count at start. Per-video download progress is
    /// broadcast via the same downloads_update as extract_audio.
    pub async fn import_playlist(
        self: &Arc<Self>,
        list_id: &str,
    ) -> Result<PlaylistImportInfo, String> {
        let url = format!("https://www.youtube.com/playlist?list={list_id}");
        let items = format!("1:{PLAYLIST_IMPORT_MAX}");
        let stdout = run_yt_dlp(
            &[
                "--dump-single-json",
                "--flat-playlist",
                "--playlist-items",
                &items,
                &url,
            ],
            time::Duration::from_secs(PLAYLIST_FLAT_TIMEOUT_SECS),
        )
        .await
        .map_err(|e| format!("Failed to expand playlist: {e}"))?;
        let meta: Value = serde_json::from_slice(&stdout)
            .map_err(|e| format!("Failed to parse playlist metadata: {e}"))?;

        // Exclude non-video entries and duplicates (same video appearing multiple times)
        let mut video_ids: Vec<String> = Vec::new();
        for entry in meta["entries"].as_array().map_or(&[][..], |v| v) {
            if let Some(id) = entry["id"].as_str()
                && is_video_id(id)
                && !video_ids.iter().any(|v| v == id)
            {
                video_ids.push(id.to_string());
            }
        }
        if video_ids.is_empty() {
            return Err("Playlist has no importable videos".to_string());
        }

        // Truncate playlist name to the creation limit (fall back to list ID if title is unknown)
        let name: String = meta["title"]
            .as_str()
            .map(str::trim)
            .filter(|t| !t.is_empty())
            .unwrap_or(list_id)
            .chars()
            .take(PLAYLIST_NAME_MAX_CHARS)
            .collect();

        // Append to an existing playlist with the same name (avoid duplicates on re-import)
        let playlist = match self.playlists().await.into_iter().find(|p| p.name == name) {
            Some(p) => p,
            None => {
                let p = self
                    .create_playlist(&name)
                    .await
                    .ok_or("Failed to create playlist")?;
                self.broadcast_playlists().await;
                p
            }
        };

        let total = video_ids.len();
        let state = self.clone();
        let cancel_gen = self.import_cancel_gen.load(Ordering::Relaxed);
        tokio::spawn(async move {
            let mut imported = 0;
            for video_id in &video_ids {
                if state.import_cancel_gen.load(Ordering::Relaxed) != cancel_gen {
                    tracing::info!(
                        "Playlist import cancelled: '{}' ({imported}/{total} imported)",
                        playlist.name
                    );
                    break;
                }
                let url = format!("https://www.youtube.com/watch?v={video_id}");
                match state.extract_audio(&url).await {
                    Ok(track) => {
                        state.add_playlist_track(&playlist.id, &track.id).await;
                        // Reflect each successfully imported track in the lists
                        state.broadcast_tracks().await;
                        state.broadcast_playlists().await;
                        imported += 1;
                    }
                    // Failures are shown via download progress error display; log only
                    Err(e) => tracing::warn!("Playlist import: skipping {video_id}: {e}"),
                }
            }
            tracing::info!(
                "Playlist import finished: '{}' ({imported}/{total} imported)",
                playlist.name
            );
        });

        Ok(PlaylistImportInfo { name, total })
    }

    fn parse_pending(
        device_id: &str,
        result: redis::RedisResult<Option<String>>,
    ) -> Option<PendingCommand> {
        let json_str = match result {
            Ok(Some(s)) => s,
            Ok(None) => return None,
            Err(e) => {
                tracing::warn!("Redis error reading pending for {device_id}: {e}");
                return None;
            }
        };
        match serde_json::from_str(&json_str) {
            Ok(cmd) => Some(cmd),
            Err(e) => {
                tracing::warn!("Discarding unparsable pending command for {device_id}: {e}");
                None
            }
        }
    }
}

// ════════════════════════════════════════
// Utilities
// ════════════════════════════════════════

/// Truncate a command's stderr to the first 300 chars for error messages.
pub fn stderr_snippet(out: &std::process::Output) -> String {
    snippet(&String::from_utf8_lossy(&out.stderr))
}

/// Truncate to the first 300 chars for error messages.
fn snippet(s: &str) -> String {
    s.chars().take(300).collect()
}

/// Extract the percentage from a yt-dlp progress line (PROGRESS_PREFIX + " 23.4%" etc.).
/// Returns None for non-progress lines or indeterminate values ("N/A" / non-finite),
/// since f64::parse accepts "nan"/"inf" which become null in JSON.
fn parse_progress_percent(line: &str) -> Option<f64> {
    let rest = line.strip_prefix(PROGRESS_PREFIX)?;
    rest.trim()
        .strip_suffix('%')?
        .trim()
        .parse()
        .ok()
        .filter(|p: &f64| p.is_finite())
}

/// Run yt-dlp and return stdout on success within the timeout.
/// On failure or timeout, return an error message (including stderr snippet).
pub async fn run_yt_dlp(args: &[&str], timeout: time::Duration) -> Result<Vec<u8>, String> {
    let cmd = Command::new("yt-dlp").args(args).output();
    let out = time::timeout(timeout, cmd)
        .await
        .map_err(|_| "yt-dlp timed out".to_string())?
        .map_err(|e| format!("Failed to run yt-dlp: {e}"))?;

    if !out.status.success() {
        return Err(format!("yt-dlp failed: {}", stderr_snippet(&out)));
    }
    Ok(out.stdout)
}

/// Fetch metadata JSON via yt-dlp (no download).
async fn fetch_metadata(url: &str) -> Result<Value, String> {
    let stdout = run_yt_dlp(
        &["--dump-json", "--no-download", url],
        time::Duration::from_secs(METADATA_TIMEOUT_SECS),
    )
    .await
    .map_err(|e| format!("Failed to fetch metadata: {e}"))?;

    serde_json::from_slice(&stdout).map_err(|e| format!("Failed to parse metadata: {e}"))
}

/// Return the next (dir=1) or previous (dir=-1) track relative to current_id.
/// Wraps around at the ends. If current_id is not found (deleted etc.),
/// returns the first (dir=1) or last (dir=-1) track.
fn neighbor_track(tracks: &[AudioTrack], current_id: &str, dir: isize) -> Option<AudioTrack> {
    if tracks.is_empty() {
        return None;
    }
    let len = tracks.len() as isize;
    let idx = match tracks.iter().position(|t| t.id == current_id) {
        Some(i) => (i as isize + dir).rem_euclid(len),
        None if dir >= 0 => 0,
        None => len - 1,
    };
    tracks.get(idx as usize).cloned()
}

/// Pick a random track excluding current_id (returns that track if only one exists).
fn random_track_from(mut tracks: Vec<AudioTrack>, current_id: &str) -> Option<AudioTrack> {
    if tracks.len() > 1 {
        tracks.retain(|t| t.id != current_id);
    }
    if tracks.is_empty() {
        return None;
    }
    // Nanoseconds of the current time are random enough for track selection variety
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .subsec_nanos() as usize;
    Some(tracks.swap_remove(nanos % tracks.len()))
}

/// Generate a playlist ID ("pl" + time-derived value; unique enough for creation frequency).
fn new_playlist_id() -> String {
    let d = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default();
    format!("pl{:x}{:05x}", d.as_millis(), d.subsec_nanos() & 0xfffff)
}

/// Classified input URL type (video / playlist / unknown).
pub enum UrlKind {
    Video,
    Playlist(String),
    Unknown,
}

/// Classify a URL as video, playlist, or unknown. URLs containing both a video
/// ID and a playlist ID (e.g. a watch URL during playlist playback) are treated
/// as video for backward compatibility.
pub fn classify_url(url: &str) -> UrlKind {
    if extract_video_id(url).is_some() {
        UrlKind::Video
    } else if let Some(list_id) = extract_playlist_id(url) {
        UrlKind::Playlist(list_id)
    } else {
        UrlKind::Unknown
    }
}

/// Extract a YouTube playlist ID from the list= parameter. Validation is
/// minimal — whether it can be expanded is left to yt-dlp, so that auth-gated
/// lists (WL etc.) return error messages to the user.
fn extract_playlist_id(url: &str) -> Option<String> {
    use std::sync::OnceLock;

    static RE: OnceLock<Option<Regex>> = OnceLock::new();
    let re = RE
        .get_or_init(|| Regex::new(r"youtube\.com/\S*[?&]list=([a-zA-Z0-9_-]{2,})").ok())
        .as_ref()?;
    Some(re.captures(url)?.get(1)?.as_str().to_string())
}

/// Check whether a string matches the YouTube video ID format.
fn is_video_id(s: &str) -> bool {
    use std::sync::OnceLock;

    static RE: OnceLock<Option<Regex>> = OnceLock::new();
    RE.get_or_init(|| Regex::new(&format!("^{VIDEO_ID_PATTERN}$")).ok())
        .as_ref()
        .is_some_and(|re| re.is_match(s))
}

fn extract_video_id(url: &str) -> Option<String> {
    use std::sync::OnceLock;

    static PATTERNS: OnceLock<Vec<Regex>> = OnceLock::new();
    let patterns = PATTERNS.get_or_init(|| {
        [
            format!(r"(?:youtube\.com/watch\?.*v=|youtu\.be/)({VIDEO_ID_PATTERN})"),
            format!(r"youtube\.com/embed/({VIDEO_ID_PATTERN})"),
            format!(r"youtube\.com/shorts/({VIDEO_ID_PATTERN})"),
            format!(r"youtube\.com/live/({VIDEO_ID_PATTERN})"),
        ]
        .iter()
        .filter_map(|p| Regex::new(p).ok())
        .collect()
    });

    for re in patterns {
        if let Some(caps) = re.captures(url) {
            return caps.get(1).map(|m| m.as_str().to_string());
        }
    }
    None
}

/// List {video_id}.m4a files in audio_cache as (video_id, path) pairs.
fn cached_video_ids(cache_dir: &Path) -> Vec<(String, PathBuf)> {
    let Ok(entries) = std::fs::read_dir(cache_dir) else {
        return Vec::new();
    };
    entries
        .filter_map(|e| e.ok())
        .filter_map(|e| {
            let path = e.path();
            if path.extension().is_none_or(|ext| ext != AUDIO_EXT) {
                return None;
            }
            let stem = path.file_stem()?.to_str()?;
            if !is_video_id(stem) {
                return None;
            }
            Some((stem.to_string(), path))
        })
        .collect()
}

/// Return a file's mtime as UNIX seconds (falls back to current time).
fn file_mtime_f64(path: &Path) -> f64 {
    std::fs::metadata(path)
        .and_then(|m| m.modified())
        .ok()
        .and_then(|t| t.duration_since(UNIX_EPOCH).ok())
        .map(|d| d.as_secs_f64())
        .unwrap_or_else(now_f64)
}

pub fn now_f64() -> f64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs_f64()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_id_from_url_variants() {
        for url in [
            "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
            "https://youtu.be/dQw4w9WgXcQ",
            "https://www.youtube.com/embed/dQw4w9WgXcQ",
            "https://www.youtube.com/shorts/dQw4w9WgXcQ",
            "https://www.youtube.com/live/dQw4w9WgXcQ",
        ] {
            assert_eq!(
                extract_video_id(url).as_deref(),
                Some("dQw4w9WgXcQ"),
                "failed for {url}"
            );
        }
        assert_eq!(extract_video_id("https://example.com/watch?v=x"), None);
    }

    #[test]
    fn redis_json_roundtrip_preserves_is_live() {
        let track = AudioTrack {
            id: "dQw4w9WgXcQ".into(),
            title: "配信".into(),
            thumbnail: String::new(),
            duration: 0,
            channel: "ch".into(),
            is_live: true,
            created_at: 1.0,
            file_path: String::new(),
        };
        let restored = AudioTrack::from_redis_json(&track.to_redis_json()).unwrap();
        assert!(restored.is_live);
        assert!(restored.file_path.is_empty());
    }

    #[test]
    fn token_roundtrip_preserves_track_id() {
        let token = new_token("dQw4w9WgXcQ");
        assert_eq!(token_track_id(&token), "dQw4w9WgXcQ");
        // Also accepts values without '#' (legacy format or bare track IDs)
        assert_eq!(token_track_id("dQw4w9WgXcQ"), "dQw4w9WgXcQ");
    }

    #[test]
    fn auto_token_is_detectable_and_preserves_track_id() {
        let token = auto_token("dQw4w9WgXcQ");
        assert!(is_auto_token(&token));
        assert_eq!(token_track_id(&token), "dQw4w9WgXcQ");
        // Normal tokens and queue entries are not detected as auto-selected
        assert!(!is_auto_token(&new_token("dQw4w9WgXcQ")));
        assert!(!is_auto_token("dQw4w9WgXcQ"));
    }

    #[test]
    fn queue_item_serializes_flattened() {
        let item = QueueItem {
            entry: "dQw4w9WgXcQ#123".into(),
            track: AudioTrack {
                id: "dQw4w9WgXcQ".into(),
                title: "t".into(),
                thumbnail: String::new(),
                duration: 10,
                channel: String::new(),
                is_live: false,
                created_at: 0.0,
                file_path: "/tmp/a.m4a".into(),
            },
        };
        let v = serde_json::to_value(&item).unwrap();
        // entry and track fields are flattened at the same level (file_path is not exposed)
        assert_eq!(v["entry"], "dQw4w9WgXcQ#123");
        assert_eq!(v["id"], "dQw4w9WgXcQ");
        assert!(v.get("file_path").is_none());
    }

    #[test]
    fn pending_command_without_offset_defaults_to_zero() {
        // Pending commands queued before offset_ms was introduced should still parse
        let legacy = r#"{"action":"play","track":{"id":"dQw4w9WgXcQ","title":"t"}}"#;
        let cmd: PendingCommand = serde_json::from_str(legacy).unwrap();
        assert_eq!(cmd.offset_ms, 0);
    }

    /// A device playing a 10-second track at position 5s with last_update 100.0.
    fn playing_device() -> DeviceState {
        DeviceState {
            device_id: "d".into(),
            name: "n".into(),
            status: "playing".into(),
            current_track: Some(AudioTrack {
                id: "dQw4w9WgXcQ".into(),
                title: "t".into(),
                thumbnail: String::new(),
                duration: 10,
                channel: String::new(),
                is_live: false,
                created_at: 0.0,
                file_path: String::new(),
            }),
            position_ms: 5_000,
            connected: true,
            last_update: 100.0,
        }
    }

    #[test]
    fn advance_position_only_moves_while_playing_and_clamps_to_duration() {
        let mut dev = playing_device();
        dev.advance_position(102.0);
        assert_eq!(dev.position_ms, 7_000);

        // Clamp at track end
        dev.last_update = 102.0;
        dev.advance_position(200.0);
        assert_eq!(dev.position_ms, 10_000);

        // Don't advance if not playing
        dev.status = "paused".into();
        dev.position_ms = 1_000;
        dev.advance_position(300.0);
        assert_eq!(dev.position_ms, 1_000);
    }

    #[test]
    fn apply_keeps_position_consistent_with_last_update() {
        // Even without an explicit position, the estimated position doesn't rewind
        let mut dev = playing_device();
        dev.apply(DeviceUpdate::new(), 102.0);
        assert_eq!(dev.position_ms, 7_000);
        assert_eq!(dev.last_update, 102.0);

        // Explicit position is adopted as-is
        let mut dev = playing_device();
        dev.apply(DeviceUpdate::new().position(1_000), 102.0);
        assert_eq!(dev.position_ms, 1_000);
        assert_eq!(dev.last_update, 102.0);
    }

    #[test]
    fn failure_record_counts_consecutive_failures() {
        let mut rec = FailureRecord::default();

        // Consecutive as long as failures happen at the same position
        assert_eq!(rec.record(5_000, 100.0), 1);
        assert_eq!(rec.record(5_000, 105.0), 2);
        assert_eq!(rec.record(5_000, 110.0), 3);

        // A failure at a later position resets the count (evidence of a successful retry in between)
        assert_eq!(rec.record(30_000, 115.0), 1);

        // A failure that hasn't advanced (e.g. restart failure) counts as consecutive
        assert_eq!(rec.record(0, 120.0), 2);

        // A failure more than FAILURE_RESET_SECS after the last one also resets
        assert_eq!(rec.record(0, 120.0 + FAILURE_RESET_SECS + 1.0), 1);
    }

    #[test]
    fn parses_progress_lines() {
        assert_eq!(
            parse_progress_percent(&format!("{PROGRESS_PREFIX} 23.4%")),
            Some(23.4)
        );
        assert_eq!(
            parse_progress_percent(&format!("{PROGRESS_PREFIX}100.0%")),
            Some(100.0)
        );
        // Ignore lines with indeterminate percentage or non-progress output
        assert_eq!(
            parse_progress_percent(&format!("{PROGRESS_PREFIX}N/A")),
            None
        );
        assert_eq!(
            parse_progress_percent("[download] Destination: x.m4a"),
            None
        );
        // Reject non-finite values accepted by f64::parse (they become null in JSON)
        assert_eq!(
            parse_progress_percent(&format!("{PROGRESS_PREFIX}nan%")),
            None
        );
        assert_eq!(
            parse_progress_percent(&format!("{PROGRESS_PREFIX}inf%")),
            None
        );
    }

    #[test]
    fn download_status_serializes_lowercase() {
        // Pin the wire format to match the frontend (types.ts) status union
        for (status, expected) in [
            (DownloadStatus::Metadata, "metadata"),
            (DownloadStatus::Downloading, "downloading"),
            (DownloadStatus::Processing, "processing"),
            (DownloadStatus::Error, "error"),
        ] {
            assert_eq!(serde_json::to_value(status).unwrap(), json!(expected));
        }
    }

    /// Minimal track for tests.
    fn track(id: &str) -> AudioTrack {
        AudioTrack {
            id: id.into(),
            title: id.into(),
            thumbnail: String::new(),
            duration: 10,
            channel: String::new(),
            is_live: false,
            created_at: 0.0,
            file_path: String::new(),
        }
    }

    #[test]
    fn neighbor_track_wraps_and_falls_back() {
        let tracks = vec![
            track("aaaaaaaaaa1"),
            track("aaaaaaaaaa2"),
            track("aaaaaaaaaa3"),
        ];

        // Forward: advance to next, wrap from last to first
        assert_eq!(
            neighbor_track(&tracks, "aaaaaaaaaa1", 1).unwrap().id,
            "aaaaaaaaaa2"
        );
        assert_eq!(
            neighbor_track(&tracks, "aaaaaaaaaa3", 1).unwrap().id,
            "aaaaaaaaaa1"
        );
        // Backward: go to previous, wrap from first to last
        assert_eq!(
            neighbor_track(&tracks, "aaaaaaaaaa2", -1).unwrap().id,
            "aaaaaaaaaa1"
        );
        assert_eq!(
            neighbor_track(&tracks, "aaaaaaaaaa1", -1).unwrap().id,
            "aaaaaaaaaa3"
        );
        // Not found (deleted etc.): first / last
        assert_eq!(
            neighbor_track(&tracks, "gone", 1).unwrap().id,
            "aaaaaaaaaa1"
        );
        assert_eq!(
            neighbor_track(&tracks, "gone", -1).unwrap().id,
            "aaaaaaaaaa3"
        );
        // Empty returns None
        assert!(neighbor_track(&[], "aaaaaaaaaa1", 1).is_none());
    }

    #[test]
    fn random_track_excludes_current_unless_only_one() {
        // With 2 tracks, the other one is always picked
        let tracks = vec![track("aaaaaaaaaa1"), track("aaaaaaaaaa2")];
        for _ in 0..5 {
            let picked = random_track_from(tracks.clone(), "aaaaaaaaaa1").unwrap();
            assert_eq!(picked.id, "aaaaaaaaaa2");
        }
        // With only 1 track, that track is returned
        let only = vec![track("aaaaaaaaaa1")];
        assert_eq!(
            random_track_from(only, "aaaaaaaaaa1").unwrap().id,
            "aaaaaaaaaa1"
        );
        assert!(random_track_from(Vec::new(), "aaaaaaaaaa1").is_none());
    }

    #[test]
    fn classifies_urls() {
        assert!(matches!(
            classify_url("https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
            UrlKind::Video
        ));
        // URL with both v= and list= is treated as video
        assert!(matches!(
            classify_url("https://www.youtube.com/watch?v=dQw4w9WgXcQ&list=PL0123456789abcdefghij"),
            UrlKind::Video
        ));
        match classify_url("https://www.youtube.com/playlist?list=PL0123456789abcdefghij") {
            UrlKind::Playlist(id) => assert_eq!(id, "PL0123456789abcdefghij"),
            _ => panic!("expected playlist"),
        }
        // watch?list= without v= is also treated as playlist
        assert!(matches!(
            classify_url("https://www.youtube.com/watch?list=PL0123456789abcdefghij"),
            UrlKind::Playlist(_)
        ));
        // Short special list IDs like WL are also accepted (expansion is left to yt-dlp)
        assert!(matches!(
            classify_url("https://www.youtube.com/playlist?list=WL"),
            UrlKind::Playlist(_)
        ));
        assert!(matches!(
            classify_url("https://example.com/watch?v=x"),
            UrlKind::Unknown
        ));
        assert!(matches!(
            classify_url("https://www.youtube.com/feed/library"),
            UrlKind::Unknown
        ));
    }

    #[test]
    fn video_id_format_check() {
        assert!(is_video_id("dQw4w9WgXcQ"));
        assert!(!is_video_id("short"));
        assert!(!is_video_id("dQw4w9WgXcQ-too-long"));
    }

    #[test]
    fn playlist_ids_are_distinct() {
        // No duplicates even when generated consecutively (nanosecond precision)
        let a = new_playlist_id();
        let b = new_playlist_id();
        assert_ne!(a, b);
        assert!(a.starts_with("pl"));
    }

    #[test]
    fn redis_json_without_is_live_defaults_to_false() {
        let legacy = r#"{"id":"dQw4w9WgXcQ","title":"t","thumbnail":"","duration":10,"channel":"","created_at":1.0,"file_path":"/tmp/a.m4a"}"#;
        let track = AudioTrack::from_redis_json(legacy).unwrap();
        assert!(!track.is_live);
    }
}
