name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  rustfmt:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Check formatting
        run: cargo fmt --all --check
